### ISSUE TITLE
setCanvas throws a spanner in window rendering

### ISSUE THREAD

**Issue by renb0** [TurtleP/nest#4]
If `love.graphics.setCanvas(someCanvas)` is called during `love.draw` callback, nest can no longer render to its current screen canvas, after using `.setCanvas()` with no args.

A solution that i can think of would be to override `setCanvas()`

```lua
local originalSetCanvas = love.graphics.setCanvas
local lastScreenCanvas = nil
function love.graphics.setCanvas(...)
    local arg = {...}
    
    if #arg == 1 and (screen == "left" or screen == "right" or screen == "bottom") then
        lastScreenCanvas = arg[1] -- Store the current screens canvas, as to be restored in a later call
    end

    if #arg == 0 and lastScreenCanvas then
        -- Restore the last screens canvas
        originalSetCanvas(lastScreenCanvas)
    else
        -- Nothing to restore, just call the original setCanvas with the args provided
        originalSetCanvas(unpack(arg))
    end
end

-- This code wasnt tested, please treat it as pseudocode
```

I wanted to get your opinion on it, as i'm very in-confident with my code/lua abilities.

**Comment by TurtleP** [comment]
Apologies on the late reply.. but huh, I've never noticed this. Definitely an oversight on my part. Feel free to open a pull request!
